[package]
name = "bfcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
clap-stdin = "0.6.0"
phf = { version = "0.11", features = ["macros"] }
